### ISSUE TITLE
composer update hofff/contao-tawk-to contao/conflicts

### ISSUE THREAD

**Issue by dp-designpilot** [hofff/contao-tawk-to#1]
Hallo Nicky

Ich wollte die tawak.to Erweiterung installieren und (gottseidank habe ich zuerst einen Test durchgeführt) nun ist es zu einem Fehler gekommen, kannst Du da was machen ???

composer update hofff/contao-tawk-to contao/conflicts
> Resolving dependencies using Composer Cloud v3.1.0
!!! Current server is sponsored by: Contao Association !!!
[7.4MiB/0.18s] Loading composer repositories with package information
[57.6MiB/1.36s] Updating dependencies
[1103.2MiB/7.47s] Your requirements could not be resolved to an installable set of packages.
[1103.2MiB/7.47s] 
  Problem 1
    - contao/manager-bundle is locked to version 4.11.2 and an update of this package was not requested.
    - hofff/contao-tawk-to 2.1.0 requires symfony/dependency-injection ^3.3 || ^4.0 -> satisfiable by symfony/dependency-injection[v3.3.0, ..., v3.4.47, v4.0.0, ..., v4.4.21].
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.21.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.20.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.19.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.18.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.17.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.16.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.47.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.46.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.45.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.44.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.43.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.42.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.41.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.40.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.39.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.38.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.37.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.36.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.35.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.34.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.33.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.32.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.31.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.30.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.29.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.28.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.27.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.26.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.25.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.24.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.23.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.22.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.21.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.20.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.19.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.18.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.17.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.16.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.18.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.17.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.16.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.0.
    - contao/manager-bundle 4.11.2 requires symfony/debug-bundle 4.4.* || 5.2.* -> satisfiable by symfony/debug-bundle[v5.2.4].
    - Root composer.json requires hofff/contao-tawk-to ^2.1 -> satisfiable by hofff/contao-tawk-to[2.1.0].
[1103.2MiB/7.47s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[45.4MiB/8.43s] Memory usage: 45.39MB (peak: 1104.36MB), time: 8.44s.
[45.4MiB/8.44s] Finished Composer Cloud resolving.

Beste Grüsse
Didier

**Comment by frontendschlampe** [comment]
wir haben unsererseits keine Probleme mit der Installation. Bitte führe eine Komplettaktualisierung oder ein `composer update` durch.
