### ISSUE TITLE
composer update hofff/contao-tawk-to contao/conflicts

### ISSUE THREAD

**Issue by dp-designpilot** [hofff/contao-tawk-to#2]
Hallo Nicky

Anbei noch meine composer.json wo ist denn das Problem, weil ich hab ja über den Contao Manager das Update gemacht
und trotzdem habe ich die Fehlermeldung die vom letzten Issues https://github.com/hofff/contao-tawk-to/issues/1

{
"type": "project",
"require": {
"christianbarkowsky/contao-tiny-compress-images": "^1.0",
"codefog/contao-elements-filter": "^1.1",
"codefog/contao-social_images": "^3.7",
"contao/calendar-bundle": "4.11.",
"contao/comments-bundle": "4.11.",
"contao/conflicts": "@dev",
"contao/faq-bundle": "4.11.",
"contao/listing-bundle": "4.11.",
"contao/manager-bundle": "4.11.",
"contao/news-bundle": "4.11.",
"contao/newsletter-bundle": "4.11.",
"dieschittigs/contao-recaptcha": "^1.2",
"dklemmt/contao_dk_mmenu": "^3.2",
"do-while/contao-backupdb-bundle": "^1.4",
"e-spin/form-newsletter-bundle": "^1.0",
"erdmannfreunde/contao-grid-bundle": "^1.0",
"erdmannfreunde/euf_hero": "^2.0",
"erdmannfreunde/euf_overlay": "^1.3",
"fritzmg/contao-facebook-js-sdk": "^3.2",
"jrgregory/m17-sticky-backend-footer": "^2.0",
"markocupic/contao-crm-bundle": "^1.0",
"markocupic/preloader-overlay": "^1.0",
"numero2/contao-opengraph3": "^4.1",
"oveleon/contao-company-bundle": "^1.2",
"oveleon/contao-member-notification": "^1.0",
"oveleon/contao-recommendation-bundle": "^1.0",
"plenta/contao-countup-bundle": "^1.0",
"srhinow/themecontent-bundle": "^0.2.0",
"terminal42/contao-changelanguage": "^3.1",
"terminal42/contao-easy_themes": "^2.2",
"terminal42/contao-folderpage": "^2.0",
"terminal42/contao-leads": "^1.4",
"terminal42/contao-pageimage": "^4.0",
"terminal42/notification_center": "^1.5"
},
"extra": {
"contao-component-dir": "assets"
},
"scripts": {
"post-install-cmd": [
"Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication"
],
"post-update-cmd": [
"Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication"
]
},
"conflict": {
"symfony/framework-bundle": ">=5"
}
}

Grüsse
Didier

**Comment by frontendschlampe** [comment]
Hey @dp-designpilot

du kannst auch in geschlossene Tickets kommentieren! ;-)

Du musst alle Erweiterungen im manager aktualisieren. Also erst den Button "Pakete aktualisieren" betätigen, dann die Erweiterung `hofff/contao-tawk-to` hinzufügen und dann "Änderungen anwenden". Oder wie bereits geschrieben im Manager unter "Systemwartung" → "Composer-Abhängigkeiten" → "Composer Update ausführen".

Damit werden alle Abhängigkeiten neu aufgelöst.
